reports:
    app_event_counts:
        description: Clicks and other events by users searching on Android and iOS apps
        granularity: days
        starts: 2014-12-05
        funnel: true
        type: script
    app_event_counts_langproj_breakdown:
        description: Clicks and other events by users searching on Android and iOS apps broken down by language
        granularity: days
        starts: 2017-03-01
        funnel: true
        max_data_points: 30
        type: script
    app_event_counts_langproj_breakdown_history:
        description: Clicks and other events by users searching on Android and iOS apps broken down by language. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    app_load_times:
        description: User-perceived load times when searching on Android and iOS apps
        granularity: days
        starts: 2014-12-05
        funnel: true
        type: script
    invoke_source_counts:
        description: How the user initiated their search session on the Android app
        granularity: days
        starts: 2016-07-28
        funnel: true
        type: script
    click_position_counts:
        description: The position of the clicked search result on the Android app
        granularity: days
        starts: 2016-07-28
        funnel: true
        type: script
    mobile_event_counts:
        description: Clicks and other events by users searching on mobile web
        granularity: days
        starts: 2015-06-11
        funnel: true
        type: script
    mobile_event_counts_langproj_breakdown:
        description: Clicks and other events by users searching on mobile web broken down by language-project pairs
        granularity: days
        starts: 2017-03-01
        max_data_points: 30
        funnel: true
        type: script
    mobile_event_counts_langproj_breakdown_history:
        description: Clicks and other events by users searching on mobile web broken down by language-project pairs. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    mobile_load_times:
        description: User-perceived load times when searching on mobile web
        granularity: days
        starts: 2015-06-11
        type: script
    desktop_event_counts:
        description: Clicks and other events by users searching on desktop
        granularity: days
        starts: 2015-04-14
        funnel: true
        type: script
    desktop_event_counts_langproj_breakdown:
        description: Clicks and other events by users searching on desktop broken down by language-project pairs
        granularity: days
        starts: 2017-03-01
        max_data_points: 30
        funnel: true
        type: script
    desktop_event_counts_langproj_breakdown_history:
        description: Clicks and other events by users searching on desktop broken down by language-project pairs. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    desktop_load_times:
        description: User-perceived load times when searching on desktop
        granularity: days
        starts: 2015-04-14
        type: script
    paulscore_approximations:
        description: Relevancy of our desktop search as measured by [PaulScore](https://www.mediawiki.org/wiki/Wikimedia_Discovery/Search/Glossary#PaulScore)
        granularity: days
        starts: 2016-10-25
        funnel: true
        type: script
    paulscore_approximations_fulltext_langproj_breakdown:
        description: Relevancy of our fulltext desktop search as measured by [PaulScore](https://www.mediawiki.org/wiki/Wikimedia_Discovery/Search/Glossary#PaulScore) broken down by language-project pairs
        granularity: days
        starts: 2017-03-01
        max_data_points: 30
        funnel: true
        type: script
    paulscore_approximations_fulltext_langproj_breakdown_history:
        description: Relevancy of our fulltext desktop search as measured by [PaulScore](https://www.mediawiki.org/wiki/Wikimedia_Discovery/Search/Glossary#PaulScore) broken down by language-project pairs. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    sample_page_visit_ld:
        description: How long users last on pages they arrived at from the search results page, computed like [median lethal dose in toxicology](https://en.wikipedia.org/wiki/Median_lethal_dose)
        granularity: days
        starts: 2015-09-02
        type: script
    search_api_usage:
        description: Counts of calls made to our various APIs
        granularity: days
        starts: 2015-05-01
        funnel: true
        type: script
    search_threshold_pass_rate:
        description: Proportion of users having search sessions longer than a predetermined threshold (10s)
        granularity: days
        starts: 2015-09-02
        type: script
    search_threshold_pass_rate_langproj_breakdown:
        description: Proportion of users having search sessions longer than a predetermined threshold (10s) broken down by language-project pairs
        granularity: days
        starts: 2017-03-01
        max_data_points: 30
        funnel: true
        type: script
    search_threshold_pass_rate_langproj_breakdown_history:
        description: Proportion of users having search sessions longer than a predetermined threshold (10s) broken down by language-project pairs. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    cirrus_query_aggregates_no_automata:
        description: Zero results rate (ZRR), excluding known bots/tools
        granularity: days
        starts: 2015-12-11
        type: script
    cirrus_query_aggregates_with_automata:
        description: Overall zero results rate (ZRR)
        granularity: days
        starts: 2015-12-11
        type: script
    cirrus_query_breakdowns_no_automata:
        description: Zero results rate (ZRR) broken down by full-text vs. prefix searches, excluding known bots/tools
        granularity: days
        starts: 2015-12-11
        funnel: true
        type: script
    cirrus_query_breakdowns_with_automata:
        description: Zero results rate (ZRR) broken down by full-text vs. prefix searches
        granularity: days
        starts: 2015-12-11
        funnel: true
        type: script
    cirrus_suggestion_breakdown_no_automata:
        description: Zero results rate (ZRR) of searches with suggestions, excluding known bots/tools
        granularity: days
        starts: 2015-12-11
        type: script
    cirrus_suggestion_breakdown_with_automata:
        description: Zero results rate (ZRR) of searches with suggestions
        granularity: days
        starts: 2015-12-11
        type: script
    cirrus_langproj_breakdown_no_automata:
        description: Zero results and total searches broken down by language-project pairs (e.g. German Wikiquote ZRR vs. French Wikibooks ZRR), excluding known bots/tools
        granularity: days
        starts: 2016-11-01
        funnel: true
        max_data_points: 30
        type: script
    cirrus_langproj_breakdown_no_automata_history:
        description: Zero results and total searches broken down by language-project pairs (e.g. German Wikiquote ZRR vs. French Wikibooks ZRR), excluding known bots/tools. Historical data store.
        granularity: days
        starts: 2017-06-01
        funnel: true
        type: script
    cirrus_langproj_breakdown_with_automata:
        description: Zero results and total searches broken down by language-project pairs (e.g. German Wikiquote ZRR vs. French Wikibooks ZRR)
        granularity: days
        starts: 2016-11-01
        funnel: true
        max_data_points: 30
        type: script
    cirrus_langproj_breakdown_with_automata_history:
        description: Zero results and total searches broken down by language-project pairs (e.g. German Wikiquote ZRR vs. French Wikibooks ZRR). Historical data store.
        granularity: days
        starts: 2017-06-01
        funnel: true
        type: script
    sister_search_traffic:
        description: Traffic to various wikis from Wikipedia search results pages; broken up by language, destination type (SERP vs not), and access method (desktop vs mobile web); exlcudes known automata
        granularity: days
        starts: 2017-06-01
        funnel: true
        type: script
    sister_search_prevalence:
        description: Prevalence of sister search results on Wikipedia search result pages; broken up by language
        granularity: days
        starts: 2017-07-01
        funnel: true
        type: script
    srp_survtime:
        description: Estimates (via survival analysis) of how long Wikipedia searchers stay on full-text search results page after getting there from autocomplete search, split by English vs French and Catalan vs other languages.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    pageviews_from_fulltext_search:
        description: Number of searches, pageviews and users to articles from full-text search, broken down by access method (desktop vs mobile web) and agent type (user vs spider).
        granularity: days
        starts: 2017-08-01
        funnel: true
        type: script
    search_result_pages:
        description: Number of searches, search result pages and users, broken down by access method (desktop vs mobile web) and agent type (user vs spider).
        granularity: days
        starts: 2017-08-01
        funnel: true
        type: script
    desktop_return_rate:
        description: Number of searches with at least a click and the number of searches that return to the same search page after clickthrough; Number of sessions with at least a click and the number of sessions that return to search for different things after clickthrough.
        granularity: days
        starts: 2017-04-01
        type: script
    mobile_session_counts:
        description: Number of user sessions on mobile web, broken down by high, medium and low volume.
        granularity: days
        starts: 2017-04-01
        type: script
