#!/bin/bash

hive -S --hiveconf mapred.job.queue.name=nice \
  --hiveconf start_date=$1 --hiveconf end_date=$2 \
  -f sister_search_prevalence.hql 2> /dev/null | grep -v parquet.hadoop | grep -v WARN:
