#!/bin/bash

hive -S --hiveconf mapred.job.queue.name=nice -e "USE event;
WITH deduplicated AS (
  SELECT DISTINCT
    wiki AS wiki_id,
    event.uniqueId AS event_id,
    event.searchSessionId AS session_id,
    MD5(LOWER(TRIM(event.query))) AS query_hash,
    INSTR(event.extraParams, '\"iw\":') > 0 AS has_iw -- sister project results shown
  FROM SearchSatisfaction
  WHERE CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) >= '$1'
    AND CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2'
    AND event.source = 'fulltext'
    AND event.action = 'searchResultPage'
    AND event.subTest IS NULL
    AND wiki RLIKE 'wiki$'
)
SELECT
  '$1' AS date, wiki_id,
  SUM(IF(has_iw, 1, 0)) AS has_sister_results,
  SUM(IF(has_iw, 0, 1)) AS no_sister_results
FROM deduplicated
GROUP BY '$1', wiki_id
HAVING has_sister_results > 0 AND no_sister_results > 0
ORDER BY '$1', wiki_id
LIMIT 100000;
" 2> /dev/null | grep -v parquet.hadoop | grep -v WARN:
