databases:
    el:
        host: analytics-store.eqiad.wmnet
        port: 3306
        creds_file: /etc/mysql/conf.d/discovery-stats-client.cnf
        db: log
defaults:
    db: el
reports:
    actions_per_tool:
        description: Actions broken down by feature (e.g. GeoHack)
        granularity: days
        starts: 2015-08-04
        funnel: true
        type: sql
    users_per_feature:
        description: Counts of users broken down by feature (e.g. GeoHack)
        granularity: days
        starts: 2015-08-04
        funnel: true
        type: sql
    users_by_country:
        description: Counts of users broken down by top 10 countries
        granularity: days
        starts: 2016-02-06
        funnel: true
        type: script
    tile_aggregates_with_automata:
        description: Tile counts by style, zoom level, etc.
        granularity: days
        starts: 2015-08-28
        funnel: true
        type: script
    tile_aggregates_no_automata:
        description: Tile counts by style, zoom level, etc., excluding those made by bots/tools
        granularity: days
        starts: 2015-12-10
        funnel: true
        type: script
