reports:
    api_cirrus_arima:
        description: ARIMA-modelled forecasts of Cirrus API usage by non-automata users
        granularity: days
        starts: 2017-02-01
        type: script
    api_cirrus_bsts:
        description: BSTS-modelled forecasts of Cirrus API usage by non-automata users
        granularity: days
        starts: 2017-02-01
        type: script
    zrr_overall_arima:
        description: ARIMA-modelled forecasts of zero results rate, excluding known bots/tools
        granularity: days
        starts: 2017-02-01
        type: script
    zrr_overall_bsts:
        description: BSTS-modelled forecasts of zero results rate, excluding known bots/tools
        granularity: days
        starts: 2017-02-01
        type: script
