#!/bin/bash

hive -S --hiveconf mapred.job.queue.name=nice -e "
USE event;
SELECT
  '$1' AS date,
  CASE WHEN (
         useragent.os_family IN('Android', 'iOS')
         OR INSTR(useragent.browser_family, 'Mobile') > 0
         OR INSTR(useragent.device_family, 'Phone') > 0
       ) THEN 'Mobile'
       ELSE 'Desktop' END AS device,
  CASE WHEN INSTR(event.destination, 'itunes.apple.com') > 0 THEN 'iOS app link'
       WHEN INSTR(event.destination, 'play.google.com') > 0 THEN 'Android app link'
       ELSE 'List of apps' END AS clicked,
  COUNT(*) AS clicks
FROM WikipediaPortal
WHERE CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) >= '$1'
  AND CONCAT(year, '-', LPAD(month, 2, '0'), '-', LPAD(day, 2, '0')) < '$2'
  AND event.cohort = 'baseline'
  AND event.event_type = 'clickthrough'
  AND event.section_used = 'other projects'
  AND (
    INSTR(event.event_destination, 'itunes.apple.com') > 0
    OR INSTR(event.destination, 'play.google.com') > 0
    OR event.destination = 'https://en.wikipedia.org/wiki/List_of_Wikipedia_mobile_applications'
  )
GROUP BY
  '$1',
  CASE WHEN (
         useragent.os_family IN('Android', 'iOS')
         OR INSTR(useragent.browser_family, 'Mobile') > 0
         OR INSTR(useragent.device_family, 'Phone') > 0
       ) THEN 'Mobile'
       ELSE 'Desktop' END,
  CASE WHEN INSTR(event.destination, 'itunes.apple.com') > 0 THEN 'iOS app link'
       WHEN INSTR(event.destination, 'play.google.com') > 0 THEN 'Android app link'
       ELSE 'List of apps' END;
" 2> /dev/null | grep -v parquet.hadoop | grep -v WARN:
