databases:
    el:
        host: db1108.eqiad.wmnet
        port: 3306
        creds_file: /etc/mysql/conf.d/discovery-stats-client.cnf
        db: log
defaults:
    db: el
    group: analytics-search-users
reports:
    pageviews:
        description: Wikipedia.org Portal pageviews, broken down by high-volume clients vs. low-volume clients
        granularity: days
        starts: 2016-01-29
        type: script
    referer_data:
        description: Pageviews broken down by referrer class (e.g. internal vs external)
        granularity: days
        starts: 2016-02-01
        funnel: true
        type: script
    user_agent_data:
        description: Wikipedia.org Portal visitors' browsers
        granularity: days
        starts: 2016-01-20
        funnel: true
        type: script
    dwell_metrics:
        description: Wikipedia.org Portal visitors' dwell-time metrics
        granularity: days
        starts: 2015-11-22
        type: script
    language_destination:
        description: The language of the Wikipedia that the Portal visitors went to
        granularity: days
        starts: 2015-11-16
        funnel: true
        type: script
    language_switching:
        description: Number of times users switched the language of the search box on Wikipedia.org Portal
        granularity: days
        starts: 2016-09-13
        type: script
    country_data:
        description: Sampled traffic to Wikipedia.org Portal from top 10 countries
        granularity: days
        starts: 2015-12-23
        funnel: true
        type: script
    all_country_data:
        description: Sampled traffic to Wikipedia.org Portal, broken down by country
        granularity: days
        starts: 2016-10-14
        max_data_points: 60
        funnel: true
        type: script
    all_country_data_history:
        description: Sampled traffic to Wikipedia.org Portal, broken down by country. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    app_link_clicks:
        description: Clicks to Wikipedia mobile apps and list of apps
        granularity: days
        starts: 2016-11-01
        funnel: true
        type: sql
    last_action_country:
        description: Last action performed on Wikipedia.org Portal per user session
        granularity: days
        starts: 2016-10-14
        max_data_points: 60
        funnel: true
        type: script
    last_action_country_history:
        description: Last action performed on Wikipedia.org Portal per user session. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    most_common_country:
        description: Most common action performed on Wikipedia.org Portal per user session, broken down by country
        granularity: days
        starts: 2016-10-14
        max_data_points: 60
        funnel: true
        type: script
    most_common_country_history:
        description: Most common action performed on Wikipedia.org Portal per user session, broken down by country. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    first_visits_country:
        description: Action performed on Wikipedia.org Portal on each user's initial visit, broken down by country
        granularity: days
        starts: 2016-10-14
        max_data_points: 60
        funnel: true
        type: script
    first_visits_country_history:
        description: Action performed on Wikipedia.org Portal on each user's initial visit, broken down by country. Historical data store.
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    clickthrough_rate:
        description: Last action (no action vs clickthrough) by Wikipedia.org Portal visitors
        granularity: days
        starts: 2015-11-18
        funnel: true
        type: script
    clickthrough_sisterprojects:
        description: Clicks to Wikimedia projects from Wikipedia.org Portal
        granularity: days
        starts: 2016-10-01
        funnel: true
        type: script
    clickthrough_firstvisit:
        description: Action performed on Wikipedia.org Portal on each user's initial visit
        granularity: days
        starts: 2015-12-31
        type: script
    clickthrough_breakdown:
        description: Last action (no action vs clickthrough) by Wikipedia.org Portal visitors, broken down by section
        granularity: days
        starts: 2015-11-18
        funnel: true
        type: script
    most_common_per_visit:
        description: Most common action performed on Wikipedia.org Portal per user session
        granularity: days
        starts: 2016-05-05
        funnel: true
        type: script
    pageviews_by_device:
        description: Pageviews broken down by device (desktop vs mobile)
        granularity: days
        starts: 2017-08-01
        funnel: true
        type: script
    clickthrough_by_device:
        description: Clickthroughs from Wikipedia.org Portal, broken down by device (desktop vs mobile)
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
    mobile_use_us_elsewhere:
        description: Number of Wikipedia.org Portal visitors on mobile devices in U.S. vs everywhere else
        granularity: days
        starts: 2017-04-01
        funnel: true
        type: script
