---
output: md_document
note: >
  Needs to be knit into Markdown and rsync'd to stat1005:/srv/published-datasets/discovery/README.md
---

# Discovery Datasets

These files are generated by Discovery's [Golden](https://github.com/wikimedia/wikimedia-discovery-golden/) data retrieval codebase that executes daily and uses [Reportupdater](https://wikitech.wikimedia.org/wiki/Analytics/Systems/Reportupdater) infrastructure. These datasets provide the metrics that are used by [Discovery's Dashboards](https://discovery.wmflabs.org/)

Last updated on `r format(Sys.Date(), "%d %B %Y")`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(width = 10000)
print_reports <- function(reports) {
  for (module in unique(reports$module)) {
    cat(sprintf("\n## %s", module), "/\n\n", sep = "")
    for (i in which(reports$module == module)) {
      cat("- **", reports$report[i], ".tsv**: ", reports$description[i], "\n", sep = "")
    }
  }
}
```

## Daily Metrics

```{r yamls_metrics}
config_yamls <- list.files(path = "../modules/metrics", pattern = "^config\\.yaml$", recursive = TRUE, full.names = TRUE)
names(config_yamls) <- sub("../modules/metrics/", "", dirname(config_yamls), fixed = TRUE)
metrics <- dplyr::bind_rows(lapply(config_yamls, function(path) {
  config_yaml <- suppressMessages(suppressWarnings(data.tree::as.Node(yaml::yaml.load_file(path))))
  reports <- data.tree::ToDataFrameTable(config_yaml[["reports"]], "report" = "name", "description")
  reports$path = paste0(file.path(dirname(path), reports$report), ifelse(reports$type == "sql", ".sql", ""))
  return(reports)
}), .id = "module")
```

```{r results='asis'}
print_reports(metrics)
```
